App\Form\Model\NacionalidadDto:
  properties:
    nombre:
      - NotBlank: ~
      - Length:
          min: 3
          max: 50
          minMessage: 'The name must be at least {{ limit }} characters long'
          maxMessage: 'The title cannot be longer than {{ limit }} characters'
          allowEmptyString: false